Fixed incorrect returncode handling for package-query

diff --git a/pun b/pun
--- a/pun
+++ b/pun
@@ -2,7 +2,7 @@
 #
 # pun - Pacman Update Notifier
 # 
-# v0.7 / 2015.06.24
+# v0.8 / 2015.06.30
 #
 # © 2015 Bernd Busse, Daniel Jankowski
 # Licensed under the LGPLv3
@@ -20,7 +20,7 @@ function print_usage() {
 
 function print_version() {
     echo "pun - Pacman Update Notifier"
-    echo "Version v0.6 - © Bernd Busse, Daniel Jankowski"
+    echo "Version v0.8 - © Bernd Busse, Daniel Jankowski"
 }
 
 function print_help() {
@@ -35,7 +35,7 @@ function print_help() {
     echo "    -v                                Force output of updates list"
     echo "         --cron                       Only print if a mail would be send (cron mail compatible)"
     echo "    -q ; --quiet                      Quiet mode, only errors are printed"
-    echo "    -m ; --mail ADDRESS               Send update-list via mail to ADDRESS"
+    echo "    -m ; --mail ADDRESS               Send update-list via mail to ADDRESS"/etc/lvm/lvm.conf.pacnew
     echo "    -t ; --telegram ID                Send update-list via telegram to contact ID"
     echo "         --telegram-token TOKEN       API-Token for the telegram telegram bot"
     echo ""
@@ -52,10 +52,8 @@ function check_err() {
     unset t_std t_err t_ret
     eval "$( eval "${1}" 2> >(t_err=$( cat ); typeset -p t_err) > >(t_std=$( cat ); typeset -p t_std); t_ret=$?; typeset -p t_ret )"
 
-    if (( $t_ret != 0 )); then
-        echo "Error:${2:+ ${2}:} $( echo -e "${t_err}" )" >&2
-        exit 1
-    elif [[ "${1}" == *"mail"* ]]; then
+    # Application specific testing
+    if [[ "${1}" == *"mail"* ]]; then
         if (( $( echo "$t_err" | grep -e 'executable not found' 2>&1 > /dev/null; echo $? ) == 0 )); then
             echo "Error:${2:+ ${2}:} $( echo "$t_err" | head -n 1 )" >&2
             exit 1
@@ -64,6 +62,10 @@ function check_err() {
         if (( $( echo "$t_err" | grep -e 'curl error: ' 2>&1 > /dev/null; echo $? ) == 0 )); then
             echo "Error:${2:+ ${2}}" >&2
             exit 1
+        fi
+        if [[ -z "$t_std" ]]; then
+            # Ignore return code if updatelist is empty
+            exit 0
         fi
     elif [[ "${1}" == *"curl "* ]]; then
         if (( $( echo "$t_std" | grep -e '\<html\>' 2>&1 > /dev/null; echo $? ) == 0 )); then
@@ -75,6 +77,12 @@ function check_err() {
             echo "Error: Telegram API: (${code}) ${description}" >&2
             exit 1
         fi
+    fi
+    
+    # Default: return code != 0
+    if (( $t_ret != 0 )); then
+        echo "Error:${2:+ ${2}:} $( echo -e "${t_err}" )" >&2
+        exit 1
     fi
 
     echo "$t_std"
@@ -310,7 +318,7 @@ if (( $? != 0 )); then
     exit $?
 fi
 
-num_pkg="$( echo -e "${pkg_list}" | wc -l )"
+num_pkg="$( echo -en "${pkg_list:+${pkg_list}\n}" | wc -l )"
 last_upd="$( grep -e 'starting full system upgrade' /var/log/pacman.log | sed -re 's/^\[([0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2})\]\s.*$/\1/g' | tail -n -1 )"
 
 # print message
